version: "3.8"

services:
  deno-article-parser:
    restart: always
    container_name: deno-article-parser
    build:
      context: .
      dockerfile: docker/deno.dockerfile
    ports:
      - "8080:8080"

  fetcher:
    container_name: fetcher
    build:
      context: .
      dockerfile: docker/cargo.dockerfile
      target: fetcher
    depends_on:
      - deno-article-parser
      - surrealdb
    environment:
      DENO_SERVER_URL: "http://deno-article-parser:8080"
      RUST_LOG: debug

  rater:
    container_name: rater
    restart: always
    build:
      context: .
      dockerfile: docker/cargo.dockerfile
      target: rater
    depends_on:
      - surrealdb
    environment:
      RUST_LOG: debug

  surrealdb:
    container_name: surrealdb
    restart: always
    # image: surrealdb/surrealdb:1.0.0-beta.10 # see https://github.com/surrealdb/surrealdb/issues/2574
    image: 1.0.0-beta.9-20230402
    env_file:
      - .env
    entrypoint:
      - /surreal
      - start
      - --user
      - $db_user
      - --pass
      - $db_password
      - --log
      - trace
      - file:/db
    volumes:
      - ./db:/db
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD", "/surreal", "isready", "-c", "http://localhost:8000"]
      retries: 5
      start_period: 20s
      timeout: 10s
