version: "3.8"

services:
  deno-article-parser:
    restart: always
    container_name: deno-article-parser
    build:
      context: .
      dockerfile: docker/deno.dockerfile
    ports:
      - "8080:8080"

  fetcher:
    container_name: fetcher
    restart: on-failure:5
    build:
      context: .
      dockerfile: docker/cargo.dockerfile
      target: fetcher
    depends_on:
      - deno-article-parser
      - surrealdb
    environment:
      deno_server_url: "http://deno-article-parser:8080"
      surrealdb_host: "surrealdb:8000"
      chrome_headless: "true"
      RUST_LOG: "debug"

  rater:
    container_name: rater
    restart: on-failure:5
    build:
      context: .
      dockerfile: docker/cargo.dockerfile
      target: rater
    depends_on:
      - surrealdb
    environment:
      RUST_LOG: debug

  surrealdb:
    container_name: surrealdb
    restart: always
    image: surrealdb/surrealdb:1.0.0 # https://github.com/surrealdb/surrealdb/issues/2704
    env_file:
      - .env
    user: root
    entrypoint:
      - /surreal
      - start
      - --user
      - $db_user
      - --pass
      - $db_password
      - --auth
      - --log
      - trace
      - file:/db
    volumes:
      - ./db:/db
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD", "/surreal", "isready"]
      retries: 5
      start_period: 20s
      timeout: 10s
