version: "3.8"

services:
  article-parser:
    restart: always
    container_name: article-parser
    build:
      context: .
      dockerfile: docker/article-parser.dockerfile
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      retries: 5
      start_period: 20s
      timeout: 10s

  fetcher:
    container_name: fetcher
    restart: on-failure:3
    build:
      context: .
      dockerfile: docker/cargo.dockerfile
      target: fetcher
    depends_on:
      - article-parser
      - surrealdb
    environment:
      article_parser_url: "http://article-parser:8080"
      surrealdb_host: "surrealdb:8000"
      chrome_headless: "true"
      RUST_LOG: "fetcher=trace"

  rater:
    container_name: rater
    restart: on-failure:3
    build:
      context: .
      dockerfile: docker/cargo.dockerfile
      target: rater
    depends_on:
      - surrealdb
    environment:
      RUST_LOG: "rater=trace"
      surrealdb_host: "surrealdb:8000"

  surrealdb:
    container_name: surrealdb
    restart: always
    image: surrealdb/surrealdb:1.0.0 # https://github.com/surrealdb/surrealdb/issues/2704
    env_file:
      - .env
    user: root
    entrypoint:
      - /surreal
      - start
      - --user
      - $db_user
      - --pass
      - $db_password
      - --auth
      - --log
      - trace
      - --deny-all
      - file:/db
    volumes:
      - ./db:/db
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD", "/surreal", "isready"]
      retries: 5
      start_period: 20s
      timeout: 10s
