FROM denoland/deno:alpine
WORKDIR /app
COPY . /app
RUN apk add --no-cache curl
CMD ["deno", "task", "run"]


# FROM node:20.8.0-alpine3.18
# WORKDIR /app
# COPY . /app
# RUN npm i
# CMD ["npm", "run", "start"]
